### ISSUE TITLE
Symfony 3

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [knpuniversity/symfony2-rest#16]
How can I use symfony 3 with rest from your tutorial?
Isn't clear how to do It inside tutorial

**Comment by bocharsky-bw** [comment]
Hey @AlessandroMinoccheri ,

We upgraded our project to Symfony 3 in [episode 4](https://knpuniversity.com/screencast/symfony-rest4) of REST series. If you'd like to see the finished code of first 3 tutorials in Symfony 3, download the code from episode 4 and check out the start directory!

Does it help you?

Cheers!

**Comment by AlessandroMinoccheri** [comment]
I can't really find how or where to download It, I have seen episode 4 and its page but no code to download.. can you help me?

**Comment by bocharsky-bw** [comment]
Hey @AlessandroMinoccheri , yes, sure! You can find "Download" button in the right up corner where you can download "Course Code":

<img width="1335" alt="screen shot 2017-02-05 at 19 26 43" src="https://cloud.githubusercontent.com/assets/3317635/22628261/9edd9234-ebd9-11e6-8ecb-d750664c699b.png">

But this feature available only for paid subscriptions or if you bought the course.

**Comment by AlessandroMinoccheri** [comment]
Ok, that was the problem! I can't find the download link because I haven't paid.

Thanks for your help!

P.S: I thought that download could be free :(

**Comment by bocharsky-bw** [comment]
Unfortunately, it doesn't. We provide free course content so everyone can read it, but course code, video and content as PDF file are available only for paid users.
