### ISSUE TITLE
Verification of created resources

### ISSUE THREAD

**Issue by peterrehm** [knpuniversity/symfony2-rest#5]
In the tutorial it would be great to adress a common need with a maybe a bit more complicated solution.

Lets assume you have an endpoint to create a user and you submit the payload to the API to create the user "Leanna Pelham" you want to make sure that you have the user afterwards in your database and you can read his data.

I would assume you have the following behat scenario then:

``` yml
  Scenario: Add Customer
    Given Database structure is initialized
    And I have the payload:
    """
    {
      "firstname": "Leanna",
      "lastname" : "Pelham"
    }
    """
  When I request "POST /api/programmers"
  Then the response body should equals:
    """
    {"data":{"id":1,"firstName":"Leanna","lastName":"Pelham","createdAt":{"date":"2016-02-10 17:20:10.000000","timezone_type":3,"timezone":"Europe\/Berlin"}}}
    """
```

The problem is you want to confirm first and lastname but you do not know the id and the created date.

Same in a slightly different scenario:

``` yml
Feature: API Access
  In order to sync data with other systems
  As a API user
  I need to access the API and get the appropriate results

  Scenario: Test customers JSON
    Given Database structure is initialized
    And there are the customers
      | customerType | companyName   | country   |
      | COMPANY      | Muster GmbH   | de        |

    When I request "GET api/customers/1"
    Then the response body should equals:
    """
    {"data":{"id":1,"companyName":"Muster GmbH", "createdAt":{"date":"2016-02-10 17:20:10.000000","timezone_type":3,"timezone":"Europe\/Berlin"}}}
    """
```

Here you do not know the id you are requesting as well as you cant know the creation date.

How would you handle that? I think those scenarios would be a great addon to the rest tutorials as this seems common functionality to me.

**Comment by weaverryan** [comment]
Hey @peterrehm!

_Part_ of this may actually be covered - because I agree, this _is_ a particularly common situation in APIs. For example, when we create a battle, we use a special syntax that allows us to get at the id: http://knpuniversity.com/screencast/rest-ep2/battle-resource-feature#creating-a-programmer-and-project-first (check the 2nd code block). This would solve your 2nd proposed scenario - you could ask for the something like `%customers.Muster GmbH.id%`.

For the first-code block, I usually just check for everything _except_ for the id. Heck, we could even build something _just_ for the id - knowing it's a problem (e.g. parse out the id in the response and put it into your "expected" json before comparing). I often check just for the _presence_ of the fields I need, and then maybe check for the specific values of just a few of them, e.g.:

``` gherkin
  Scenario: Add Customer
    Given Database structure is initialized
    And I have the payload:
    """
    {
      "firstname": "Leanna",
      "lastname" : "Pelham"
    }
    """
  When I request "POST /api/programmers"
  Then the response body should contain the following fields:
   | id |
   | companyName |
   | customerType |
  And the response "customerType" field should equal "COMPANY"
```

**Comment by peterrehm** [comment]
I improved meanwhile as I like to combine the check of the entire structure with the actual data. I want my tests to break if someone adds a field.

So my current idea is as follows:

``` json
  Scenario: Add Customer
    Given Database structure is initialized
    And I have the payload:
    """
    {
      "firstname": "Leanna",
      "lastname" : "Pelham"
    }
    """
  When I request "POST /api/programmers"
  Then the response body should equals:
    """
    {"data":{"id":((any)),"firstName":"Leanna","lastName":"Pelham","createdAt":{"date":"((any))","timezone_type":3,"timezone":"Europe\/Berlin"}}}
    """
```

And the corresponding context function file looks as follows:

``` php
    /**
     * @Then /^the response body should equals:$/
     */
    public function theResponseBodyShouldEquals(PyStringNode $expectedResponse)
    {
        $regex = json_encode(json_decode($expectedResponse->getRaw()), JSON_PRETTY_PRINT);
        $regex = '/' . preg_quote($regex, '/') . '/';
        $regex = str_replace('\(\(any\)\)', '.*', $regex);
        \PHPUnit_Framework_Assert::assertRegExp($regex, $this->response->getBody()->getContents());
    }
```

I also updated my API so that all API output is formatted with a custom JsonResponse, I think it might make sense to mention that option as well. If you transmit your data compressed the difference is not significant. And I think e.g. Github is also sending all responses formatted.

``` php
<?php

namespace AppBundle\Response;

class JsonResponse extends \Symfony\Component\HttpFoundation\JsonResponse
{
    // Encode <, >, ', &, and " for RFC4627-compliant JSON, which may also be embedded into HTML.
    // 15 === JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_PRETTY_PRINT
    protected $encodingOptions = 143;
}
```

I will check your other comment regarding the special syntax tomorrow.

**Comment by peterrehm** [comment]
@weaverryan The processReplacements() idea is great and a good solution for that use case. I must admit that I have not looked into Episode 2 so far :)
